%%%----------------------------------------------------------------------------
%%% FIX protocol record definitions
%%% @author Serge Aleynikov <saleyn@gmail.com>
%%%----------------------------------------------------------------------------
%%% Created: 2011-01-07
%%%----------------------------------------------------------------------------
%%% This file is automatically generated!  Don't modify by hand!
%%%----------------------------------------------------------------------------

%% Generic FIX message
-record(fix, {
      version
    , msgType
    , senderCompID
    , targetCompID
    , msgSeqNum
    , sendingTime
    , body        :: tuple()
}).

%% Message type: 0
-record(heartbeat, {
      opt = []
}).

%% Message type: 1
-record(testRequest, {
      testReqID                                       %% Tag: 112
    , opt = []
}).

%% Message type: 2
-record(resendRequest, {
      beginSeqNo                                      %% Tag: 7
    , endSeqNo                                        %% Tag: 16
    , opt = []
}).

%% Message type: 3
-record(reject, {
      refSeqNum                                       %% Tag: 45
    , opt = []
}).

%% Message type: 4
-record(sequenceReset, {
      newSeqNo                                        %% Tag: 36
    , opt = []
}).

%% Message type: 5
-record(logout, {
      opt = []
}).

%% Message type: 6
-record(indicationofInterest, {
      iOIid                                           %% Tag: 23
    , iOITransType                                    %% Tag: 28
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , iOIShares                                       %% Tag: 27
    , opt = []
}).

%% Message type: 7
-record(advertisement, {
      advId                                           %% Tag: 2
    , advTransType                                    %% Tag: 5
    , symbol                                          %% Tag: 55
    , advSide                                         %% Tag: 4
    , shares                                          %% Tag: 53
    , opt = []
}).

%% Message type: 8
-record(executionReport, {
      orderID                                         %% Tag: 37
    , execID                                          %% Tag: 17
    , execTransType                                   %% Tag: 20
    , execType                                        %% Tag: 150
    , ordStatus                                       %% Tag: 39
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , leavesQty                                       %% Tag: 151
    , cumQty                                          %% Tag: 14
    , avgPx                                           %% Tag: 6
    , opt = []
}).

%% Message type: 9
-record(orderCancelReject, {
      orderID                                         %% Tag: 37
    , clOrdID                                         %% Tag: 11
    , origClOrdID                                     %% Tag: 41
    , ordStatus                                       %% Tag: 39
    , cxlRejResponseTo                                %% Tag: 434
    , opt = []
}).

%% Message type: A
-record(logon, {
      encryptMethod                                   %% Tag: 98
    , heartBtInt                                      %% Tag: 108
    , opt = []
}).

%% Message type: B
-record(news, {
      headline                                        %% Tag: 148
    , opt = []
}).

%% Message type: C
-record(email, {
      emailThreadID                                   %% Tag: 164
    , emailType                                       %% Tag: 94
    , subject                                         %% Tag: 147
    , opt = []
}).

%% Message type: D
-record(newOrderSingle, {
      clOrdID                                         %% Tag: 11
    , handlInst                                       %% Tag: 21
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , transactTime                                    %% Tag: 60
    , ordType                                         %% Tag: 40
    , opt = []
}).

%% Message type: E
-record(newOrderList, {
      listID                                          %% Tag: 66
    , bidType                                         %% Tag: 394
    , totNoOrders                                     %% Tag: 68
    , opt = []
}).

%% Message type: F
-record(orderCancelRequest, {
      origClOrdID                                     %% Tag: 41
    , clOrdID                                         %% Tag: 11
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , transactTime                                    %% Tag: 60
    , opt = []
}).

%% Message type: G
-record(orderCancelReplaceRequest, {
      origClOrdID                                     %% Tag: 41
    , clOrdID                                         %% Tag: 11
    , handlInst                                       %% Tag: 21
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , transactTime                                    %% Tag: 60
    , ordType                                         %% Tag: 40
    , opt = []
}).

%% Message type: H
-record(orderStatusRequest, {
      clOrdID                                         %% Tag: 11
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , opt = []
}).

%% Message type: J
-record(allocation, {
      allocID                                         %% Tag: 70
    , allocTransType                                  %% Tag: 71
    , side                                            %% Tag: 54
    , symbol                                          %% Tag: 55
    , shares                                          %% Tag: 53
    , avgPx                                           %% Tag: 6
    , tradeDate                                       %% Tag: 75
    , opt = []
}).

%% Message type: K
-record(listCancelRequest, {
      listID                                          %% Tag: 66
    , transactTime                                    %% Tag: 60
    , opt = []
}).

%% Message type: L
-record(listExecute, {
      listID                                          %% Tag: 66
    , transactTime                                    %% Tag: 60
    , opt = []
}).

%% Message type: M
-record(listStatusRequest, {
      listID                                          %% Tag: 66
    , opt = []
}).

%% Message type: N
-record(listStatus, {
      listID                                          %% Tag: 66
    , listStatusType                                  %% Tag: 429
    , noRpts                                          %% Tag: 82
    , listOrderStatus                                 %% Tag: 431
    , rptSeq                                          %% Tag: 83
    , totNoOrders                                     %% Tag: 68
    , opt = []
}).

%% Message type: P
-record(allocationACK, {
      allocID                                         %% Tag: 70
    , tradeDate                                       %% Tag: 75
    , allocStatus                                     %% Tag: 87
    , opt = []
}).

%% Message type: Q
-record(dontKnowTrade, {
      orderID                                         %% Tag: 37
    , execID                                          %% Tag: 17
    , dKReason                                        %% Tag: 127
    , symbol                                          %% Tag: 55
    , side                                            %% Tag: 54
    , opt = []
}).

%% Message type: R
-record(quoteRequest, {
      quoteReqID                                      %% Tag: 131
    , opt = []
}).

%% Message type: S
-record(quote, {
      quoteID                                         %% Tag: 117
    , symbol                                          %% Tag: 55
    , opt = []
}).

%% Message type: T
-record(settlementInstructions, {
      settlInstID                                     %% Tag: 162
    , settlInstTransType                              %% Tag: 163
    , settlInstRefID                                  %% Tag: 214
    , settlInstMode                                   %% Tag: 160
    , settlInstSource                                 %% Tag: 165
    , allocAccount                                    %% Tag: 79
    , transactTime                                    %% Tag: 60
    , opt = []
}).

%% Message type: V
-record(marketDataRequest, {
      mDReqID                                         %% Tag: 262
    , subscriptionRequestType                         %% Tag: 263
    , marketDepth                                     %% Tag: 264
    , opt = []
}).

%% Message type: W
-record(marketDataSnapshotFullRefresh, {
      symbol                                          %% Tag: 55
    , opt = []
}).

%% Message type: X
-record(marketDataIncrementalRefresh, {
      opt = []
}).

%% Message type: Y
-record(marketDataRequestReject, {
      mDReqID                                         %% Tag: 262
    , opt = []
}).

%% Message type: Z
-record(quoteCancel, {
      quoteID                                         %% Tag: 117
    , quoteCancelType                                 %% Tag: 298
    , opt = []
}).

%% Message type: a
-record(quoteStatusRequest, {
      symbol                                          %% Tag: 55
    , opt = []
}).

%% Message type: b
-record(quoteAcknowledgement, {
      quoteAckStatus                                  %% Tag: 297
    , opt = []
}).

%% Message type: c
-record(securityDefinitionRequest, {
      securityReqID                                   %% Tag: 320
    , securityRequestType                             %% Tag: 321
    , opt = []
}).

%% Message type: d
-record(securityDefinition, {
      securityReqID                                   %% Tag: 320
    , securityResponseID                              %% Tag: 322
    , totalNumSecurities                              %% Tag: 393
    , opt = []
}).

%% Message type: e
-record(securityStatusRequest, {
      securityStatusReqID                             %% Tag: 324
    , symbol                                          %% Tag: 55
    , subscriptionRequestType                         %% Tag: 263
    , opt = []
}).

%% Message type: f
-record(securityStatus, {
      symbol                                          %% Tag: 55
    , opt = []
}).

%% Message type: g
-record(tradingSessionStatusRequest, {
      tradSesReqID                                    %% Tag: 335
    , subscriptionRequestType                         %% Tag: 263
    , opt = []
}).

%% Message type: h
-record(tradingSessionStatus, {
      tradingSessionID                                %% Tag: 336
    , tradSesStatus                                   %% Tag: 340
    , opt = []
}).

%% Message type: i
-record(massQuote, {
      quoteID                                         %% Tag: 117
    , opt = []
}).

%% Message type: j
-record(businessMessageReject, {
      refMsgType                                      %% Tag: 372
    , businessRejectReason                            %% Tag: 380
    , opt = []
}).

%% Message type: k
-record(bidRequest, {
      clientBidID                                     %% Tag: 391
    , bidRequestTransType                             %% Tag: 374
    , totalNumSecurities                              %% Tag: 393
    , bidType                                         %% Tag: 394
    , tradeType                                       %% Tag: 418
    , basisPxType                                     %% Tag: 419
    , opt = []
}).

%% Message type: l
-record(bidResponse, {
      opt = []
}).

%% Message type: m
-record(listStrikePrice, {
      listID                                          %% Tag: 66
    , totNoStrikes                                    %% Tag: 422
    , opt = []
}).
